### PR TITLE
fix: add createUser param to GenerateLink

### PR DESCRIPTION
**Pull request by J0**
## What is the current behavior?
See: https://github.com/supabase/gotrue-js/issues/358

## What is the new behavior?

Introduces an additional parameter to GenerateLink which allows user to generate a magic link. Further thought is needed, leaving as draft for now.

### CODE REVIEW

**Comment by activenode** [comment]
I'm slightly confused about this. Why was this closed?

**Comment by J0** [comment]
Hm yeah let me re-open this one. Thanks for flagging

**Comment by J0** [comment]
It's been a while so I can't recall but I think the initial hesitation was because `generateLink` is an admin method and probably needs less guard rails like `shouldCreateUser` 

I'll think about it + check in with team and get back. If you'd like to share more about potential use cases please feel free to do so

**Comment by J0** [comment]
Ah I think to preserve existing behaviour `shouldCreateUser` needs to default to true which is a little cumbersome at the moment.


I'll likely revisit after attending to core priorities but for now will have to trouble you to make use of a trigger or other checks.

Let me know if there are any suggestions though

**Pull request closed without merging**
