### PR TITLE
fix: customAuthHook update REST response

### PR DESCRIPTION
**Pull request by taytzehao**
## What kind of change does this PR introduce?

The `AuthTokenResponse` REST response would be updated with data that is modified by the custom access auth hook.

## What is the current behavior?

`AuthTokenResponse` REST response is not updated with data in the custom access auth hook token. #1415

## What is the new behavior?

The `User_metadata` in `User` data of the REST response is in sync `user_metadata` in the access token provided

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by tzehaoo** [comment]
@hf

**Comment by tzehaoo** [comment]
@kangmingtay , could you or somebody else please help review this PR?

**Comment by hf** [comment]
Custom Access Token Hook cannot be used to modify the user metadata, which is common with other similar features in other authentication software. There will be a different hook in the future where you could change the user metadata "before sign up" for example.

Custom Access Token hook is therefore not connected to the REST response, as it modifies the _access token_ not the User object.

**Comment by hf** [comment]
Thank you for the contribution, though! Please don't feel discouraged to contribute again!

**Pull request closed without merging**
