### PR TITLE
Azure ad provider

### PR DESCRIPTION
**Pull request by Levet**
## What kind of change does this PR introduce?

Feature: The addition of the Azure AD provider.

### CODE REVIEW

**Comment by kiwicopple** [comment]
Thanks for this @Levet . One question - do you have the link where we can sign up to create the credentials? (for our docs)

**Comment by Levet** [comment]
@kiwicopple Here's where you setup an App with Azure (you'll need an account to view it): https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps

This is Microsoft's documentation regarding creating an app to setup the callback uri, and receive the token/secret:
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**Comment by kiwicopple** [comment]
That's awesome, thanks @Levet - I'll add it to our docs once this one is merged

**Comment by Levet** [comment]
Awesome, let me know if anything else is required!

**Comment by awalias** [comment]
hey @Levet I almost have it working but am getting stuck at:

[Unable to find email with Azure provider](https://github.com/supabase/gotrue/blob/a13cf921746a582a48c5e968a0353038a18b1c99/api/provider/azure.go#L66)

I think I have it set up correctly on the azure dashboard but perhaps there's some step I'm missing

image

**Comment by awalias** [comment]
I tried adding these further permissions but still no luck

image

**Comment by Levet** [comment]
Okay, I'll check it out and get back to you with a solution.

**Comment by Levet** [comment]
@awalias  Are you using an outlook email to authenticate?

**Comment by awalias** [comment]
@Levet yea I'm using my personal one, the authentication itself seems to work fine because a valid JWT is returned, but the call to the API to fetch the user details apparently doesn't return an email or name

does the whole flow work for you? I'm aware that there are a million different ways to configure the azure app, just wary that I may be missing something on that side

**Comment by Levet** [comment]
@awalias Yeah it does work for us. I am able to replicate the error with a personal account. I took a look at the response I'm getting when I authenticate with a personal email I created. It looks like it doesn't pass the name or email with the /oidc/userinfo endpoint. But it does if I use my organization's email.

This is what I am getting back when I use my organizational account:

```
{
    "sub": "sfsy5_ht8Co5HLq1xl2o-RIN9xFUMU-O_kX2fwEJbYo",
    "name": "Jordan Levet",
    "family_name": "Levet",
    "given_name": "Jordan",
    "picture": "https://graph.microsoft.com/v1.0/me/photo/$value",
    "email": "jlevet@coltbuilders.com"
}
```

And this is what I am getting from a new user I just created, from the same endpoint:

```
{
"sub": "AAAAAAAAAAAAAAAAAAAAADkcgpeWaIJ0Fxppn8tJtSY",
"picture": "https://graph.microsoft.com/v1.0/me/photo/$value"
}
```

I think typically anyone that is going to use Azure to authenticate/authorize users in supabase will have an organization setup, so this should be a non-issue. Beyond testing of course.

I found this: https://github.com/MicrosoftDocs/azure-docs/issues/28317
They seem to describe a similar issue and mention using: https://graph.microsoft.com/v1.0/me to fetch the user information. This would require some modification to the struct to support the response that looks like this:

```
{
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
"displayName": "Jordan Levet",
"surname": "Levet",
"givenName": "Jordan",
"id": "bd709b0e3a1a20a5",
"userPrincipalName": "jordanlevet801@outlook.com",
"businessPhones": [],
"jobTitle": null,
"mail": null,https://graph.microsoft.com/oidc/userinfo
"mobilePhone": null,
"officeLocation": null,
"preferredLanguage": null
}
```

Though we have some hesitations about implementing it this way as the Azure docs seem to specify: https://graph.microsoft.com/oidc/userinfo. As seen here: https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo

**Comment by Levet** [comment]
I'm working on setting up a dev organization to check if that resolves this issue. I'll provide instructions if it does.

**Comment by Levet** [comment]
Finally got it sorted. What a pain.

1. Create a free azure account here: https://azure.microsoft.com/en-us/free/search/ (it requires CC info but since we're not using any services and wont be charged)

2. Register a new app (for whatever reason, your previous, outlook created app is gone, also this has to be multi-tenant, though its not clear why).

3. Update your client and secret in gotrue .env

4. Get your super special azure email from here: https://portal.azure.com/?quickstart=true#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview 
    a. Click on "Users". You should automatically be added. 
    b. Click on your user. 
    c. Copy the email that looks like: _{OriginalOutlookEmailName}_outlook.com#EXT#@{Domain}outlook.onmicrosoft.com_ - under the user's name. i.e. jordanlevet801_outlook.com#EXT#@jordanlevet801outlook.onmicrosoft.com

5. Attempt gotrue auth flow with above mentioned email. If you can't authenticate with your outlook password, follow the forgot password flow (it will email the original outlook email for recovery by default). _NOTE: the email described in 4c is the only email that will work, not the original outlook one. Why? Something to do with Active Directories authorization process. I don't think this is necessary if the email's domain corresponds with the azure app's_

When it requests the user info, it will get the normal outlook email, not the email mentioned in 4c.

Again this shouldn't be necessary for anyone using an account that has an Azure account presiding. They should be able to setup an app, get the token/secret and be ready to go.

It's pretty convoluted. Let me know if you have any problems.

**Comment by Levet** [comment]
Any update on this? Were you able to get authenticated?

**Comment by awalias** [comment]
hey @Levet will have another go today 👍

**Comment by awalias** [comment]
ok I made a PR to your PR (PRception) with a couple of tidies but apart from that looks good:

https://github.com/Levet/gotrue/pull/1

If you merge these then I can merge this into master 👍

**Comment by Levet** [comment]
@awalias Cool, I merged your PR :D. It has conflicts with master. I tried to resolve them, however, I don't feel confident in resolving go.sum and go.mod.

Thanks for being awesome to work with! This is actually my first open source PR and I don't work with golang often. Mainly nodejs. 

Let me know if you need anything else!

**Comment by awalias** [comment]
thanks @Levet ! This is an amazing contribution for your first :)

I fixed the conflicts and merged directly into master

I'll work on adding the necessary pieces to the supabase dashboard today and will hopefully have the changes deployed by early next week! Thanks for all your hard work on this!

**Comment by Levet** [comment]
Awesome! I have done a lot of front-end dev as well. I am happy to assist with that as well!

Thanks again, I'm actually more excited than I (maybe) should be about this first contribution. :D

**Comment by joeyboey** [comment]
Do I understand correctly that personal Azure Accounts cannot be used at all?
I have the same problem, the Azure App has all necessary scopes but auth fails with the missing email.

From my point personal accounts should be supported.

**Comment by subhaschnadraBodaki** [comment]
after i am logging using azure  i am getting Error: UNABLE TO EXCHANGE CODE 
It is working fine with google 
How can i fix this?
or is this a supabase bug?

**Comment by kangmingtay** [comment]
hey everyone, yall might wanna check out the docs [here](https://github.com/supabase/supabase/pull/4726) for setting up azure sign-in. It seems to work fine for me and i can't reproduce the error. 

Let me know if the guide helps, or if it needs to be corrected, feel free to let me know in the PR as well.

**Comment by V-Py** [comment]
Hi everyone, currently using the Login with Azure feature, works like a charm, I only have 2 questions :
- Why is it labeled as "Unofficial" in the documentation ? => https://supabase.com/docs/guides/auth
- Seems the **name of the user is not correctly passed** in the user_metada, even though after searching in the code, it looks like the information is retrieved. Since I don't know Go enough to try it myself, can someone have a look at it ? seems like a minor change/variable name maybe ? 
- 
Thanks in advance 👍 

image

**\api\provider\azure.go**

```
return &UserProvidedData{
		Metadata: &Claims{
			Issuer:        g.APIPath,
			Subject:       u.Sub,
			Name:          u.Name,
			Email:         u.Email,
			EmailVerified: true,

			// To be deprecated
			FullName:   u.Name,
			ProviderId: u.Sub,
		},
		Emails: []Email{{
			Email:    u.Email,
			Verified: true,
			Primary:  true,
		}},
	}
```

**Comment by razanfawwaz** [comment]
Hi, I'm using single-tenant settings but I got this error "Use a tenant-specific endpoint or configure the application to be multi-tenant". Which settings should I add/edit? Thanks!

**Comment by karan2801** [comment]
Are personal Azure Accounts not supported currently?

**Comment by kangmingtay** [comment]
@karan2801 they are supported, are you running into an issue with sign-in with azure?

**Comment by karan2801** [comment]
Yes @kangmingtay, I am facing issues when I am using a personal outlook email. I am getting the following error: `http://localhost:3000/?error=server_error&error_description=Error+getting+user+email+from+external+provider`. When I try the auth with a work azure email, the oauth is working fine. I have setup an app in Azure that allows accounts in any organization directory and personal accounts to access the API. Also, I have added the tenant URL as `https://login.microsoftonline.com/common`

**Comment by anthonylaflamme** [comment]
https://github.com/supabase/gotrue/issues/550#issuecomment-1586407459 @karan2801 Had that same recently but didn't had the opportunity to test they did update to retrieve more email but no clue if the solutions worked

**Comment by aar2dee2** [comment]
Hi,
I followed the [Login With Azure](https://supabase.com/docs/guides/auth/social-login/auth-azure) to setup auth with Azure in my NextJS application.
I get the following error when trying to login with Azure:
Screenshot 2023-08-05 at 11 58 26 AM

I'm using pages router in NextJS  and`"@supabase/supabase-js": "^2.28.0"`.

I've set it up to use both - organization accounts and personal accounts.

**Comment by mukulseth** [comment]
Having the same issue with personal Microsoft account. I really hope someone has found a solution. I've emailed Supabase support as well. Will report if I hear back.

**Comment by danieljsanders** [comment]
I still get this error with 

  supabase.auth.signInWithOAuth({
      provider: 'azure',
      options: {
        scopes: 'email',
        redirectTo: `${location.origin}/home`
      }
    });

**Comment by danieljsanders** [comment]
> Hi, I followed the [Login With Azure](https://supabase.com/docs/guides/auth/social-login/auth-azure) to setup auth with Azure in my NextJS application. I get the following error when trying to login with Azure: Screenshot 2023-08-05 at 11 58 26 AM
> 
> I'm using pages router in NextJS and`"@supabase/supabase-js": "^2.28.0"`.
> 
> I've set it up to use both - organization accounts and personal accounts.

I've seen this error too when trying other emails than my personal hotmail.

**Comment by karan2801** [comment]
@anthonylaflamme It hasnt worked for me, @mukulseth Let us know if you hear anything back from Supabase.

**Comment by mukulseth** [comment]
I was able to resolve the issue by setting the tenant URL to `https://login.microsoftonline.com/common`, missed that from earlier in the convo.

Some people might also not be setting the `scopes` parameter in options. `scopes: 'email'` That also results in the same error.

**Comment by aar2dee2** [comment]
> I was able to resolve the issue by setting the tenant URL to `https://login.microsoftonline.com/common`, missed that from earlier in the convo.
> 
> Some people might also not be setting the `scopes` parameter in options. `scopes: 'email'` That also results in the same error.

This worked. Thank you so much!

**Comment by daanno** [comment]
Screenshot 2025-01-08 at 21 41 59
Hi,

I've got Azure via Supabase working. As an admin tennant i've authorized the app for my org. But every time I try the login, I have to re-authorize the Azure app and even worse, users with no admin rights need to ask permission to use the Azure application.

It seems this is an Azure setting, but not sure which one? It seems the intergration is not authorized?

**Pull request merged**
