### PR TITLE
feat: add msg91 as phone provider (fork of #989)

### PR DESCRIPTION
**Pull request by hf**
Same as #989 with some technical details resolved.

### CODE REVIEW

**Comment by paigham-tech** [comment]
Hey @MeetChaudhari @hf @kangmingtay any update for this ? Went through comments on #989, it looks like this won't be merged until webhook solution is implemented. So, any idea about what is the status on webhook solution ?

This is turning out to be a blocker for Indian Startups. Hope we receive a update soon. Thanks!!

**Comment by MeetChaudhari** [comment]
> Hey @MeetChaudhari @hf @kangmingtay any update for this ? Went through comments on #989, it looks like this won't be merged until webhook solution is implemented. So, any idea about what is the status on webhook solution ?
> 
> This is turning out to be a blocker for Indian Startups. Hope we receive a update soon. Thanks!!

I completely agree with you @paigham-tech , even our startup had to go with a different implementation than supabase just due to this auth provider thing, 

But as i am aware, the webhook based auth implementation is pending from supabase team side, @hf  please correct me if i am wrong. 

@paigham-tech  As soon as supabase team implements webhook based system, ill write the webhook based integration or whatever required for Msg91 support.

**Comment by rohankm** [comment]
Waiting for this

**Comment by J0** [comment]
Hey @MeetChaudhari,

Thanks for the implementation. We're implementing it now and will circle back with further updates soon. I'm heading to India this weekend and hope to test it then if I can get a number. I'm going to close this PR for now but will reach back out once we're closer to completion on the hook implementation

Let us know if there are further queries.

Thanks

**Comment by rohankm** [comment]
> Hey @MeetChaudhari,
> 
> Thanks for the implementation. We're implementing it now and will circle back with further updates soon. I'm heading to India this weekend and hope to test it then if I can get a number. I'm going to close this PR for now but will reach back out once we're closer to completion on the hook implementation
> 
> Let us know if there are further queries.
> 
> Thanks

what is the status?

**Comment by J0** [comment]
Hey @rohankm,

Feel free to follow along on #1474. Testing some final bits.

**Comment by J0** [comment]
Hey @rohankm @MeetChaudhari,

Thanks for patiently waiting. We'll be moving forward with the Hooks implementation soon and are open to taking contributions for a msg91 -[here's what it looks like for Twilio](https://github.com/supabase/supabase/pull/23157/files#diff-03db63ea4a80645c4a8da7ca8e6980aeef719072aa4b0d16cefd8dc900860e4a) 

If you're still keen on adding Msg91 as a custom SMS provider feel free to let me know and will follow up with next steps.

Thanks!

**Comment by MeetChaudhari** [comment]
> Hey @rohankm @MeetChaudhari,
> 
> Thanks for patiently waiting. We'll be moving forward with the Hooks implementation soon and are open to taking contributions for a msg91 -[here's what it looks like for Twilio](https://github.com/supabase/supabase/pull/23157/files#diff-03db63ea4a80645c4a8da7ca8e6980aeef719072aa4b0d16cefd8dc900860e4a) 
> 
> If you're still keen on adding Msg91 as a custom SMS provider feel free to let me know and will follow up with next steps.
> 
> Thanks!
> 
> 
> 

Hey @J0,

Thanks for reaching out, yes I am still up for integration of msg91, how can we proceed.

**Comment by rohankm** [comment]
Hi,
I have already implemented msg91 and its working fine.
Here is the fork https://github.com/rohankm/gotrue.git

**Comment by MeetChaudhari** [comment]
> Hi,
> I have already implemented msg91 and its working fine.
> Here is the fork https://github.com/rohankm/gotrue.git

Hey, @rohankm 

I haven't checked the fork, but if it's based on my fork of initial implementation then it won't work as the supabase team is switching to an webhook based implementation which @J0 is talking about.

**Comment by rohankm** [comment]
> > Hi,
> > I have already implemented msg91 and its working fine.
> > Here is the fork https://github.com/rohankm/gotrue.git
> 
> Hey, @rohankm
> 
> I haven't checked the fork, but if it's based on my fork of initial implementation then it won't work as the supabase team is switching to an webhook based implementation which @J0 is talking about.

I understand but I didn't have time to wait for the supabase team to implement it and its not based on webhooks

**Comment by MeetChaudhari** [comment]
> > > Hi,
> > > I have already implemented msg91 and its working fine.
> > > Here is the fork https://github.com/rohankm/gotrue.git
> > 
> > Hey, @rohankm
> > 
> > I haven't checked the fork, but if it's based on my fork of initial implementation then it won't work as the supabase team is switching to an webhook based implementation which @J0 is talking about.
> 
> I understand but I didn't have time to wait for the supabase team to implement it and its not based on webhooks

Yup, I got it bro anyways none of our implementation will move forward, as now it has to be webhook based one, I'll start working on it as soon as @J0 pings me up with necessary stuff, I am right now studying the example implementation of twilio which he shared.

**Comment by J0** [comment]
@MeetChaudhari do you have Discord? If so I'll open a thread there with details - else I can open a Github issue or discussion in this repo and tag you

**Comment by MeetChaudhari** [comment]
> @MeetChaudhari do you have Discord? If so I'll open a thread there with details there and tag you - else I can open a Github issue or discussion in this repo and tag you
> 
> Actually, let's stick to Github for visibility - will open an issue.

My discord username - kreferlink

**Comment by rohankm** [comment]
@J0  @MeetChaudhari any progress?

**Comment by MeetChaudhari** [comment]
> @J0  @MeetChaudhari any progress?

Was Stuck in something, will start today

**Comment by J0** [comment]
No worries - feel free to ping me if there's anything confusing

**Comment by J0** [comment]
Folks, checking in - any issues here or anything we can help with?

**Comment by rohankm** [comment]
@MeetChaudhari are you working on this?

**Comment by MeetChaudhari** [comment]
> @MeetChaudhari are you working on this?

Yes, mostly it will be done within the next week or so, it's delayed as I am working on so many things together.

**Pull request closed without merging**
