### PR TITLE
feat: CreateCustomToken like firebase

### PR DESCRIPTION
**Pull request by sanmit-vartak**
## What kind of change does this PR introduce?

Introduced Customtoken with login for admin

## What is the current behavior?

https://github.com/orgs/supabase/discussions/20025

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by sanmit-vartak** [comment]
@kangmingtay

**Comment by hf** [comment]
Hey thank you for the contribution.

I looked at it and at a first glance I'm not sure this works the way you want it to. The team is hard at work on making anonymous sign-ins possible in the next two months. With that feature you would be able to do implement custom authentication systems, so it's best to wait for those features to land first.

Please don't be discouraged from contributing. If you have ideas on how to solve something, please work with the team on an issue first before committing time to code which may get rejected.

**Comment by sanmit-vartak** [comment]
Hello, Thankd for responding.
I am not looking out for anonymous sign ins. With this PR I am avoiding password login from my client, since I am using supabase as secondary service for specific usecases, I wanted to have this feature.
Firebase allowed my to create the token for specific users from service accounts which I could wrap inside my own auth and provide the access to users.
you can refer the feature: https://firebase.google.com/docs/auth/admin/create-custom-tokens

**Comment by sanmit-vartak** [comment]
Closing since feat is not neede.

**Pull request closed without merging**
