### PR TITLE
feat: add openid in keycloak scope

### PR DESCRIPTION
**Pull request by yos1p**
Bug fix related to issue: #1219

### CODE REVIEW

**Comment by kangmingtay** [comment]
hi @yos1p, thanks for your contribution! can you please fix the failing test and ensure that your PR follows the [contributing guidelines](https://github.com/supabase/gotrue/blob/master/CONTRIBUTING.md#checklist-for-submitting-pull-requests) please?

**Comment by yos1p** [comment]
@kangmingtay Should be good now with the test. Thank you!

**Comment by kangmingtay** [comment]
Hi @yos1p, what if the application is using older versions of keycloak? would specifying additional scopes like the `openid` scope result in an error returned? this would break backward compatibility and i would much rather just highlight this in the docs - we allow one to pass in the scopes through the `signInWithOAuth` method (https://supabase.com/docs/reference/javascript/auth-signinwithoauth)

**Comment by hf** [comment]
Closing as this is backward incompatible.

**Pull request closed without merging**
