### PR TITLE
feat: add Figma provider

### PR DESCRIPTION
**Pull request by bnjmnt4n**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

No provider for Figma.

## What is the new behavior?

This PR adds a new provider for Figma.

## Additional context
The Figma OAuth2 API only provides a single scope ("file_read"), so there isn't a more restrictive scope solely for getting user metadata.

Figma developer reference: https://www.figma.com/developers/api#oauth2

### CODE REVIEW

**Comment by bnjmnt4n** [comment]
Wanted to add a suggestion for the provider tests: it would be helpful to have an explicit checklist of things to test for each provider (in CONTRIBUTING.md or elsewhere). My process was to copy the tests from another provider (GitHub in this case), then modify to suit the Figma provider. Since there are lots of differences between each provider (eg. GitHub returns multiple emails whereas Figma only returns one), it's easy to miss out on tests if you're just copying and modifying from another provider's tests (which is what I presume most would do).

**Review by kangmingtay — APPROVED** [review]
lgtm - once you've finished adding the docs to https://github.com/supabase/supabase/tree/master/apps/docs/pages/guides/auth/social-login  we can merge this one in!

**Comment by bnjmnt4n** [comment]
Oops, forgot to update: made a PR for the docs + adding the Figma provider to the Studio settings at https://github.com/supabase/supabase/pull/15083. Let me know if there's any tweaks required.

**Comment by kangmingtay** [comment]
@bnjmnt4n yup a checklist does sound good, we actually have plans to refactor the oauth test suite to use [gock](https://github.com/h2non/gock) for mocking the requests and have an interface to clearly define the testing methods that need to be implemented. It's just not high on the priority list since the current tests are already functional.

**Pull request merged**
