### PR TITLE
feat: adds ability to set access_token expiry

### PR DESCRIPTION
**Pull request by i-pip**
## What kind of change does this PR introduce?

feature: Allows updating access_token via http PUT - expiry time only for now. 

## What is the current behavior?

#178 - access token config currently only read from environment variables

## Additional context

We seriously need working api tests. Currently testing using `curl`

### CODE REVIEW

**Comment by kangmingtay** [comment]
Hey @i-pip, thanks for contributing! I'm holding back on merging this PR because of the following security concerns I have:
1. `/token` endpoint is not protected behind an admin endpoint. This means that if an attacker takes over the browser session and obtains the access token, they can make calls to the `/token` endpoint and change the expiry time of the token such that it never expires.
2. The recommended practice is to issue short-lived access tokens and long-lived refresh tokens. In the event of an attack, the developer can easily revoke a refresh token and the attacker will only be limited to the duration of which the access token is valid for.

**Comment by i-pip** [comment]
Thanks for the feedback @kangmingtay i had similar concerns about having /token so easily accessible and not behind /admin but didn't have a way to test it behind /admin - that's changed now with yesterday's release ☂️ (thanks for that - makes it easier to contribute now) 

Would you recommend I put the /token endpoint behind /admin or close the PR? Your second concern I think can be addressed by setting a max expiry time (that way it's still possible to set an expiry time without breaking security)

**Comment by kangmingtay** [comment]
Hey @i-pip, yeah after discussing this with @awalias, we prefer to restrict the configuration of gotrue environment variables via the dashboard or some external secrets manager (for the self-hosting folks out there). Sorry about it, we'll close the issue as well!

**Comment by i-pip** [comment]
okay, thanks @kangmingtay

**Pull request closed without merging**
