### PR TITLE
feat: linkedin provider

### PR DESCRIPTION
**Pull request by riderx**
## What kind of change does this PR introduce?

feature, it add Linkedin Provider

## What is the current behavior?

No provider for linkedin before

## What is the new behavior?

WIP: Linkedin provider. 
Ps: i know nothing of golang and don't like it much, but i really need this provider for socialselling.ai ,so i did try to start the work 

So i did try to do it.

Few things are missing :
- tests, i didn't write or run the code i just made the biding from my js implementation
- i did try to handle catch all in type for name localization but not sure if it's handle well

Help is more than welcome :)

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by HarryET** [comment]
I added a working implementation to this in #269

**Comment by dthyresson** [comment]
Hi @riderx.

Thanks for adding these envars. 

In order for them to be recognized, could you also add the provider and config for LinkedIn as well? 

Not sure if they need to be: LINKEDIN or LINKED_IN to match a LinkedIn or LinkedIn case.

Thanks!

See: https://github.com/supabase/gotrue/blob/1dddc248fb820e638f0d54b9d51c2803295b5c1d/api/external.go#L365

and

See: https://github.com/supabase/gotrue/blob/1dddc248fb820e638f0d54b9d51c2803295b5c1d/conf/configuration.go#L82

**Comment by HarryET** [comment]
> Hi @riderx.
> 
> Thanks for adding these envars.
> 
> In order for them to be recognized, could you also add the provider and config for LinkedIn as well?
> 
> Not sure if they need to be: LINKEDIN or LINKED_IN to match a LinkedIn or LinkedIn case.
> 
> Thanks!
> 
> See:
> 
> https://github.com/supabase/gotrue/blob/1dddc248fb820e638f0d54b9d51c2803295b5c1d/api/external.go#L365
> 
> and
> 
> See:
> 
> https://github.com/supabase/gotrue/blob/1dddc248fb820e638f0d54b9d51c2803295b5c1d/conf/configuration.go#L82

Hi this isn't being implemented in this PR. It was added to my other PR #269

**Comment by HarryET** [comment]
@riderx might be worth closing this now that its been implemented in #269

**Comment by dthyresson** [comment]
Thanks @HarryET - I hadn't seen your PR #269.

I'll run a few tests later and check with @kangmingtay but agree that your PR means that this can be closed.

**Comment by HarryET** [comment]
> Thanks @HarryET - I hadn't seen your PR #269.
> 
> I'll run a few tests later and check with @kangmingtay but agree that your PR means that this can be closed.

Awesome. I still need to get my GoTrue Local Environment sorted, but from the looks of things should be working. Thanks @dthyresson

**Comment by dthyresson** [comment]
> I still need to get my GoTrue Local Environment sorted,

I setup a local GoTrue last week. Was a little bumpy, but I intend to update the docs and contributing readme to make it smoother for new contributors.

I'll be sure to cc you on the PR so you can test it out and try it out.

**Comment by HarryET** [comment]
> > I still need to get my GoTrue Local Environment sorted,
> 
> I setup a local GoTrue last week. Was a little bumpy, but I intend to update the docs and contributing readme to make it smoother for new contributors.
> 
> I'll be sure to cc you on the PR so you can test it out and try it out.

Awesome. I've really enjoyed contributing to GoTrue so far just need a better local setup to tackle issues other than providers. I don't know if you saw but I have an RFC for 2FA just need to pad it out a bit more but though about trying to get a PR rolling if that was something you were interested in?

**Comment by dthyresson** [comment]
> I have an RFC for 2FA

I did not, but a fan of 2FA and I have seen requests for this feature. I'll be sure to watch it!

**Comment by riderx** [comment]
@dthyresson thanks for the doc improvement as a newbe in golang, i wasn't able to run gotrue locally, all my code was done without been able to test anything, it was very furstrating.
Thanks a lot for the help guys

**Comment by riderx** [comment]
as @dthyresson say in https://github.com/supabase/gotrue/pull/269 it's better to have specific Pr, so I reopen this one with the fix of @HarryET

**Comment by riderx** [comment]
@HarryET took 1 hours with me to make gotrue work.
Thanks for that. @dthyresson please take this in consideration we can help the project if the install process is smooth, now 
the install process is broken, script fail we had to fix so many things.

An now I have grotrue work, does the redirect to Linkedin, and the redirect back to my test app, but I'm stuck again since I run only gotrue supabase refuse:
```
{error: "invalid_grant", error_description: "Invalid Refresh Token"}
error: "invalid_grant"
error_description: "Invalid Refresh Token"
```
Can we have a docker-compose who run everything in one time to help better ?

**Comment by riderx** [comment]
@dthyresson do you need more things to review the PR ?

**Review by kangmingtay — APPROVED** [review]

**Comment by kangmingtay** [comment]
hi @riderx, thanks for laying the groundwork for the linkedin provider! apologies for the delay, i know it's been put off for quite awhile but i've made some changes to fix [this issue](https://github.com/supabase/gotrue/pull/269#issuecomment-977748488) with the PR and also added some tests!

**Comment by riderx** [comment]
@kangmingtay thanks a lot <3 
I understand you cannot handle everything in same time, it's normal.
I would love a bit more communication about what you handle, otherwise happy to be a part of it :)

**Pull request merged**
