### PR TITLE
Messagebird SMS provider

### PR DESCRIPTION
**Pull request by MonsterDeveloper**
Hi there! This PR, based on @kangmingtay solution for OTP, introduces a new SMS provider — Messagebird. Since I don't have much Golang experience, there is more (probably) to be done, but I hope that my code will kickstart the progress of adding a new provider.

## What is the current behavior?

The only available SMS provider is Twilio.

## What is the new behavior?

By changing `GOTRUE_SMS_PROVIDER` environment variable to `messagebird` and setting respective variables for access key and sender phone number, users will be able to send SMS with OTP codes through MessageBird API.

### CODE REVIEW

**Comment by MonsterDeveloper** [comment]
Hello everyone! Any comments on my PR? Can you review it? Thanks!

**Comment by kangmingtay** [comment]
Hey @MonsterDeveloper, thanks so much for contributing a new provider for sms! It's been a really busy month for me so far and I haven't had the time to review and test this yet. Ideally, I'd prefer if there are accompanying tests for this but I know that the tests are non-existent even for the twilio provider so that's why I haven't pushed for it yet. I'll be looking at reviewing this some time in the mid-end of October.

**Review by kangmingtay — APPROVED** [review]

**Comment by kangmingtay** [comment]
Hey @MonsterDeveloper, amazing work on the PR, please reach out to me on discord at kangmingtay#7177 so we can swag you up!!

**Comment by MonsterDeveloper** [comment]
@kangmingtay that's amazing news! Thanks! I've just sent a friendship request to you on Discord (from Everjust) 😁

**Pull request merged**
