### PR TITLE
feat: support RS256 signing & verification

### PR DESCRIPTION
**Pull request by ecchochan**
Discussion: 
- https://github.com/supabase/supabase/discussions/12759

### Summary
There are 3 parts in this PR:

- Setup CI for RS256
    - [chore: setup 2 envs for testing, preparing rs256 test cases](https://github.com/supabase/gotrue/pull/985/commits/f9c160165731f27d90fb457c961abe1b139f9cd6)
- Refactoring of repeated code usage
    - [chore: abstract parseJWTToken](https://github.com/supabase/gotrue/pull/985/commits/c013d1f70e3bfdf1187b915b1484fcab30ce98b0)
    - [chore: refactor generateAccessToken](https://github.com/supabase/gotrue/pull/985/commits/2b6ff0b3c9f43c25f798b6faf407cd7e22be49db)
    - [chore: abstract usage of NewWithClaims](https://github.com/supabase/gotrue/pull/985/commits/03372106f34cff9db73a939943abba6cd9587c90)
- Added Signing using RS256
    - [feat: add rs256 capability](https://github.com/supabase/gotrue/pull/985/commits/c7456b2de2d16aca2a64efac2b90a8d651a0c95e)

### Testing
The GH action will run in the matrix of `[hs25, rs256]`
Basically each runs agains a different `test.env`:
- `test.hs256.env` - the original one before this PR
- `test.rs256.env` - a modified one with the following added
    - `GOTRUE_JWT_SECRET` - the content of `private_key.pem`
    - `GOTRUE_JWT_SIGNING_METHOD` - `RS256`
    - `GOTRUE_JWT_PUBKEY` - the content of `public_key.pem`

### How to generate a pair of `private_key.pem` and `public_key.pem`?

```bash
openssl genrsa -out private_key.pem 2048
openssl rsa -in private_key.pem -pubout -out public_key.pem
```

---
<details>
  <summary>More detailed Explanations</summary>

1. Ensure CI for RS256
    - Added a different env for testing in GH action so that the later changes can reflect a proper testing
      - [chore: setup 2 envs for testing, preparing rs256 test cases](https://github.com/supabase/gotrue/pull/985/commits/f9c160165731f27d90fb457c961abe1b139f9cd6)
2. Refactoring
    - Abstracted usage of `ParseWithClaims()` into `parseJWTToken` in `token.go`
      - [chore: abstract parseJWTToken](https://github.com/supabase/gotrue/pull/985/commits/c013d1f70e3bfdf1187b915b1484fcab30ce98b0)
    - Refactor `generateAccessToken` to accept the config object directly
      - [chore: refactor generateAccessToken](https://github.com/supabase/gotrue/pull/985/commits/2b6ff0b3c9f43c25f798b6faf407cd7e22be49db)
    - Abstracted the usage of `NewWithClaims` into `newJWTTokenWithClaims`
      - [chore: abstract usage of NewWithClaims](https://github.com/supabase/gotrue/pull/985/commits/03372106f34cff9db73a939943abba6cd9587c90)
3. Added RS256 capability
    - Added `GOTRUE_JWT_SIGNING_METHOD` (`config.JWT.SigningMethod`) to opt-in `RS256` (default to `HS256`)
    - Added `GOTRUE_JWT_PUBKEY` (`config.JWT.Pubkey`) in replacement to `GOTRUE_JWT_SECRET` for verification
    - Verify with `RS256` according to the token header; Default to `HS256` for backward compatibility
    - Updated `Webhook` to store `signingMethod` from config similar to `jwtSecret`
      - [feat: add rs256 capability](https://github.com/supabase/gotrue/pull/985/commits/c7456b2de2d16aca2a64efac2b90a8d651a0c95e)

</details>

### CODE REVIEW

**Comment by kangmingtay** [comment]
Hi @ecchochan, thanks for spending time to work on this feature. As this is a rather huge feature, we would prefer if you can spec out a RFC [here](https://github.com/supabase/rfcs) before starting work on it. Adding asymmetric JWT validation is definitely something on our roadmap in the near future but we're currently prioritising other features such as PKCE and SSO. If you need this for your own application urgently, it would be best to create a fork of gotrue and opt to self-host it. We can revisit the upstreamed changes from the fork at a later date and if it's good, we can look to merging it back into the main repo. Please let me know if you've got any questions about this!

**Comment by ecchochan** [comment]
@kangmingtay 
Hi, I split this PR into 3 parts:
- Setup CI for RS256
    - [chore: setup 2 envs for testing, preparing rs256 test cases](https://github.com/supabase/gotrue/pull/985/commits/f9c160165731f27d90fb457c961abe1b139f9cd6)
- Refactoring of repeated code usage
    - [chore: abstract parseJWTToken](https://github.com/supabase/gotrue/pull/985/commits/c013d1f70e3bfdf1187b915b1484fcab30ce98b0)
    - [chore: refactor generateAccessToken](https://github.com/supabase/gotrue/pull/985/commits/2b6ff0b3c9f43c25f798b6faf407cd7e22be49db)
    - [chore: abstract usage of NewWithClaims](https://github.com/supabase/gotrue/pull/985/commits/03372106f34cff9db73a939943abba6cd9587c90)
- Added Signing using RS256
    - [feat: add rs256 capability](https://github.com/supabase/gotrue/pull/985/commits/c7456b2de2d16aca2a64efac2b90a8d651a0c95e)

where each commit remains small enough to review, do you think they can be treated as separate PRs to merge? 
I tried to make the changes as little as possible and the 5 commits are all (almost) one change at a time.

I updated the PR description accordingly.

**Comment by hf** [comment]
Hey @ecchochan, thank you for this submission. Below are some of my thoughts on the change.

In my opinion, we should be avoiding RS256 or any of the other RSA based signing methods. RSA256 signatures are quite large and they will increase the size of the access token which can have knock-on effects in browsers, cookies and other places.

I'm also not a fan of separating the public key from the private key. With RSA this is easy, the public key can be calculated directly from the public key. (This is what we do with SAML.) With ECC it's not super easy, but thankfully common encodings like [PKCS8](https://pkg.go.dev/crypto/x509#MarshalPKCS8PrivateKey) encode both the public and private key.

I'd prefer that we give the user the option to choose what signing algorithm they want by specifying a PKCS8 encoded private key, and then GoTrue identifies the asymmetric algorithm and always uses SHA-256. 

Furthermore, this change has large security implications which I'd rather keep within the team. We are not fans of commiting to code which we don't use in production. This is a priority feature for the team, but it's not the top priority right now. This change would affect the Supabase platform at large and it's best if the change is tightly coordinated with the team. It's also backward incompatible and a system that allows users to roll keys easily without disrupting service should be considered before any change takes place.

I don't want to discourage you from contributing for the repo, but for large changes like this some tighter communication with the team would help you not waste too much time implementing the change.

**Comment by ecchochan** [comment]
@hf 
Thank you for the feedback! Indeed I do not need the public key at all!

I am actually planning to use RSA signing in my own project (requiring asymmetric signing), and would like to contribute if that helps. But I definitely understand such changes related to security would rather be handled by internal team.

I will leave the PR here, and you can feel free to close it :D

**Comment by Evertt** [comment]
@hf has the team since your last comment on this PR implemented their own way of using a public/private key?

To me this seems like such an obvious beneficial feature that I don't quite understand why this wasn't implemented from the very beginning.

Cause right now, I have to choose between using either:

* `supabase.auth.getSession()`, which is fast, but returns untrustworthy data.
* `supabase.auth.getUser()`, which return trustworthy data, but is relatively slow and may not work when the network gets flaky.

If `getSession()` would be able to locally verify the signature of the access token, then it could guarantee the validity of the data it returns, without needing an extra network request.

I can't wait for that to be implemented. 🙏

**Pull request closed without merging**
