### PR TITLE
rename Azure to Mircosoft

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Renames Azure to Mircosoft

## What is the current behavior?

Everything named Azure

## What is the new behavior?

Everything renamed Azure

## Additional context

[notion task](https://www.notion.so/supabase/Rename-Sign-In-with-Azure-to-Sign-In-With-Microsoft-de54d2d9aa524abc967370fe5cf2d95b?d=142cb170ded24ea7910d04ee3eb4524a)

### CODE REVIEW

**Comment by kangmingtay** [comment]
@Isaiah-Hamilton what was the motivation behind this change? the provider name used in gotrue-js is called `azure` and changing that would be breaking

**Comment by Isaiah-Hamilton** [comment]
> @Isaiah-Hamilton what was the motivation behind this change? the provider name used in gotrue-js is called `azure` and changing that would be breaking

The motivation behind this is the general public might relate better to sign in with microsoft as opposed to sign in with azure, [Notion task](https://www.notion.so/supabase/Rename-Sign-In-with-Azure-to-Sign-In-With-Microsoft-de54d2d9aa524abc967370fe5cf2d95b?d=142cb170ded24ea7910d04ee3eb4524a). But now seeing how much we would have to change I think it would be better to maybe only update the docs.

**Comment by kangmingtay** [comment]
yeah that's true, maybe we can rename the stuff in the docs to `Azure (Microsoft)` ? would that be clearer?

**Comment by J0** [comment]
Hey @Isaiah-Hamilton,

Apologies on this, I should have thought through this further.

Perhaps let's close this PR and rename the  docs to `Azure (Microsoft)`  as @kangmingtay has suggested?

**Pull request closed without merging**
