### PR TITLE
Add Zoom OAuth

### PR DESCRIPTION
**Pull request by devkiran**
## What kind of change does this PR introduce?

Add [Zoom OAuth ](https://marketplace.zoom.us/docs/guides/auth/oauth)

## What is the current behavior?

Login with Zoom was not available.

## What is the new behavior?

Now the users can configure the Zoom OAuth.

## Additional context

NA

### CODE REVIEW

**Comment by J0** [comment]
@devkiran Thanks for this PR! We'll review it as soon as we can and get back to you shortly :)

**Review by J0 — APPROVED** [review]
I've tested it locally and this looks good to me, thank you so much for your contribution! Feel free to dm me at J0 on Discord if you'd like some swag.

Could we trouble you to add documentation on how to use the provider as well?

**Links**
 
Documentation repo: https://github.com/supabase/supabase/tree/master/web/docs/guides/auth

Example of provider documentation: https://supabase.com/docs/guides/auth/auth-google

Feel free to let us know if you need any help with this!

**Comment by devkiran** [comment]
@J0 See https://github.com/supabase/supabase/pull/5221

**Comment by J0** [comment]
@devkiran thank you so much for your contribution!

**Pull request merged**
